FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -yq g++-multilib cmake clang git nano python3 python3-pip autoconf libtool

RUN python3 -m pip install wheel git+https://github.com/alliedmodders/ambuild

WORKDIR /alliedmodders

ENV CXX="g++"
ENV CC="gcc"
